import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "@/components/providers/AppWrapper";
import { SessionProvider } from "next-auth/react";
import { EditorStoreProvider } from "@/components/providers/EditorStoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          <EditorStoreProvider>{children}</EditorStoreProvider>
        </AppWrapper>
      </body>
    </html>
  );
}
